# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myBox"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myBox_faceBottom_Fa0_Ctr0():
	P000 = App.Vector(10.0000, 0.0000, 0)
	P001 = App.Vector(110.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(117.0711, 2.9289, 0)
	P003 = App.Vector(120.0000, 10.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(120.0000, 70.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(117.0711, 77.0711, 0)
	P006 = App.Vector(110.0000, 80.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(10.0000, 80.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(2.9289, 77.0711, 0)
	P009 = App.Vector(0.0000, 70.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(0.0000, 10.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(2.9289, 2.9289, 0)
	P012 = App.Vector(10.0000, 0.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myBox_faceBottom_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(60.0000, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_myBox_faceBottom_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.5000, App.Vector(71.2500, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myBox_faceBottom_Fa0():
	FC000 = ctr_face_myBox_faceBottom_Fa0_Ctr0()
	FC001 = ctr_face_myBox_faceBottom_Fa0_Ctr1()
	FC002 = ctr_face_myBox_faceBottom_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def myBox_faceBottom():
	FA000 = face_myBox_faceBottom_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myBox_faceTop_Fa0_Ctr0():
	P000 = App.Vector(10.0000, 0.0000, 0)
	P001 = App.Vector(110.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(117.0711, 2.9289, 0)
	P003 = App.Vector(120.0000, 10.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(120.0000, 70.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(117.0711, 77.0711, 0)
	P006 = App.Vector(110.0000, 80.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(10.0000, 80.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(2.9289, 77.0711, 0)
	P009 = App.Vector(0.0000, 70.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(0.0000, 10.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(2.9289, 2.9289, 0)
	P012 = App.Vector(10.0000, 0.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myBox_faceTop_Fa0_Ctr1():
	P000 = App.Vector(10.0000, 2.0000, 0)
	P001 = App.Vector(110.0000, 2.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(115.6569, 4.3431, 0)
	P003 = App.Vector(118.0000, 10.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(118.0000, 70.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(115.6569, 75.6569, 0)
	P006 = App.Vector(110.0000, 78.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(10.0000, 78.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(4.3431, 75.6569, 0)
	P009 = App.Vector(2.0000, 70.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(2.0000, 10.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(4.3431, 4.3431, 0)
	P012 = App.Vector(10.0000, 2.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myBox_faceTop_Fa0():
	FC000 = ctr_face_myBox_faceTop_Fa0_Ctr0()
	FC001 = ctr_face_myBox_faceTop_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def myBox_faceTop():
	FA000 = face_myBox_faceTop_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myBox_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(80.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(80.0000, 40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(78.0000, 40.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(78.0000, 2.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(2.0000, 2.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(2.0000, 40.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(0.0000, 40.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(0.0000, 0.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myBox_faceSide_Fa0():
	FC000 = ctr_face_myBox_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myBox_faceSide():
	FA000 = face_myBox_faceSide_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myBox_faceFace_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(120.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(120.0000, 40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(118.0000, 40.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(118.0000, 2.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(2.0000, 2.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(2.0000, 40.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(0.0000, 40.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(0.0000, 0.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myBox_faceFace_Fa0():
	FC000 = ctr_face_myBox_faceFace_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myBox_faceFace():
	FA000 = face_myBox_faceFace_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myBox_bottom():
	FIG = myBox_faceBottom()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myBox_bottom = fex_subpax_myBox_bottom()

def fex_subpax_myBox_top():
	FIG = myBox_faceTop()
	VEX = FIG.extrude(App.Vector(0, 0, 38))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 2.0000))
	return VFP
subpax_myBox_top = fex_subpax_myBox_top()

def fvol_pax_myBox():
	V000 = subpax_myBox_bottom
	V001 = V000.fuse(subpax_myBox_top)
	VFC = V001.removeSplitter()
	return VFC
pax_myBox = fvol_pax_myBox()


pax_myBox.check()
#pax_myBox.exportBrep(f"{outFileName}.brep")
#pax_myBox.exportIges(f"{outFileName}.igs")
#pax_myBox.exportStep(f"{outFileName}.stp")
pax_myBox.exportStl(f"{outFileName}.stl")

