# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "surface"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_surface_faceSurface_Fa0_Ctr0():
	P000 = App.Vector(-4353.3333, -500.0000, 0)
	P001 = App.Vector(-2753.3333, -500.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-2753.3333, 500.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-4353.3333, 500.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-4353.3333, -500.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa0():
	FC000 = ctr_face_surface_faceSurface_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa1_Ctr0():
	P000 = App.Vector(-2743.3333, -1510.0000, 0)
	P001 = App.Vector(-1143.3333, -1510.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-1143.3333, -510.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-2743.3333, -510.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-2743.3333, -1510.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa1():
	FC000 = ctr_face_surface_faceSurface_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa2_Ctr0():
	P000 = App.Vector(-2743.3333, -500.0000, 0)
	P001 = App.Vector(-1143.3333, -500.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-1143.3333, 500.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-2743.3333, 500.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-2743.3333, -500.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa2():
	FC000 = ctr_face_surface_faceSurface_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa3_Ctr0():
	P000 = App.Vector(-2743.3333, 510.0000, 0)
	P001 = App.Vector(-1143.3333, 510.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-1143.3333, 1510.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-2743.3333, 1510.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-2743.3333, 510.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa3():
	FC000 = ctr_face_surface_faceSurface_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa4_Ctr0():
	P000 = App.Vector(-800.0000, -2520.0000, 0)
	P001 = App.Vector(800.0000, -2520.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.0000, -1520.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-800.0000, -1520.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-800.0000, -2520.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa4():
	FC000 = ctr_face_surface_faceSurface_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa5_Ctr0():
	P000 = App.Vector(-800.0000, -1510.0000, 0)
	P001 = App.Vector(800.0000, -1510.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.0000, -510.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-800.0000, -510.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-800.0000, -1510.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa5():
	FC000 = ctr_face_surface_faceSurface_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa6_Ctr0():
	P000 = App.Vector(-800.0000, -500.0000, 0)
	P001 = App.Vector(800.0000, -500.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.0000, 500.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-800.0000, 500.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-800.0000, -500.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa6():
	FC000 = ctr_face_surface_faceSurface_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa7_Ctr0():
	P000 = App.Vector(-800.0000, 510.0000, 0)
	P001 = App.Vector(800.0000, 510.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.0000, 1510.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-800.0000, 1510.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-800.0000, 510.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa7():
	FC000 = ctr_face_surface_faceSurface_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa8_Ctr0():
	P000 = App.Vector(-800.0000, 1520.0000, 0)
	P001 = App.Vector(800.0000, 1520.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.0000, 2520.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-800.0000, 2520.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-800.0000, 1520.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa8():
	FC000 = ctr_face_surface_faceSurface_Fa8_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa9_Ctr0():
	P000 = App.Vector(1143.3333, -1510.0000, 0)
	P001 = App.Vector(2743.3333, -1510.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2743.3333, -510.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1143.3333, -510.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1143.3333, -1510.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa9():
	FC000 = ctr_face_surface_faceSurface_Fa9_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa10_Ctr0():
	P000 = App.Vector(1143.3333, -500.0000, 0)
	P001 = App.Vector(2743.3333, -500.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2743.3333, 500.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1143.3333, 500.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1143.3333, -500.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa10():
	FC000 = ctr_face_surface_faceSurface_Fa10_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa11_Ctr0():
	P000 = App.Vector(1143.3333, 510.0000, 0)
	P001 = App.Vector(2743.3333, 510.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2743.3333, 1510.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1143.3333, 1510.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1143.3333, 510.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa11():
	FC000 = ctr_face_surface_faceSurface_Fa11_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa12_Ctr0():
	P000 = App.Vector(2753.3333, -500.0000, 0)
	P001 = App.Vector(4353.3333, -500.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(4353.3333, 500.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(2753.3333, 500.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2753.3333, -500.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa12():
	FC000 = ctr_face_surface_faceSurface_Fa12_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def surface_faceSurface():
	FA000 = face_surface_faceSurface_Fa0()
	FA001 = face_surface_faceSurface_Fa1()
	FA002 = face_surface_faceSurface_Fa2()
	FA003 = face_surface_faceSurface_Fa3()
	FA004 = face_surface_faceSurface_Fa4()
	FA005 = face_surface_faceSurface_Fa5()
	FA006 = face_surface_faceSurface_Fa6()
	FA007 = face_surface_faceSurface_Fa7()
	FA008 = face_surface_faceSurface_Fa8()
	FA009 = face_surface_faceSurface_Fa9()
	FA010 = face_surface_faceSurface_Fa10()
	FA011 = face_surface_faceSurface_Fa11()
	FA012 = face_surface_faceSurface_Fa12()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007, FA008, FA009, FA010, FA011, FA012])
	rOneFig.check()
	return rOneFig

def ctr_face_surface_faceOnePanel_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(1600.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1600.0000, 1000.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1000.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceOnePanel_Fa0():
	FC000 = ctr_face_surface_faceOnePanel_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def surface_faceOnePanel():
	FA000 = face_surface_faceOnePanel_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_surface_panel_0():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-4353.3333, -500.0000, 0.0000))
	return VFP
subpax_surface_panel_0 = fex_subpax_surface_panel_0()

def fex_subpax_surface_panel_1():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-2743.3333, -1510.0000, 0.0000))
	return VFP
subpax_surface_panel_1 = fex_subpax_surface_panel_1()

def fex_subpax_surface_panel_2():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-2743.3333, -500.0000, 0.0000))
	return VFP
subpax_surface_panel_2 = fex_subpax_surface_panel_2()

def fex_subpax_surface_panel_3():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-2743.3333, 510.0000, 0.0000))
	return VFP
subpax_surface_panel_3 = fex_subpax_surface_panel_3()

def fex_subpax_surface_panel_4():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-800.0000, -2520.0000, 0.0000))
	return VFP
subpax_surface_panel_4 = fex_subpax_surface_panel_4()

def fex_subpax_surface_panel_5():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-800.0000, -1510.0000, 0.0000))
	return VFP
subpax_surface_panel_5 = fex_subpax_surface_panel_5()

def fex_subpax_surface_panel_6():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-800.0000, -500.0000, 0.0000))
	return VFP
subpax_surface_panel_6 = fex_subpax_surface_panel_6()

def fex_subpax_surface_panel_7():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-800.0000, 510.0000, 0.0000))
	return VFP
subpax_surface_panel_7 = fex_subpax_surface_panel_7()

def fex_subpax_surface_panel_8():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-800.0000, 1520.0000, 0.0000))
	return VFP
subpax_surface_panel_8 = fex_subpax_surface_panel_8()

def fex_subpax_surface_panel_9():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(1143.3333, -1510.0000, 0.0000))
	return VFP
subpax_surface_panel_9 = fex_subpax_surface_panel_9()

def fex_subpax_surface_panel_10():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(1143.3333, -500.0000, 0.0000))
	return VFP
subpax_surface_panel_10 = fex_subpax_surface_panel_10()

def fex_subpax_surface_panel_11():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(1143.3333, 510.0000, 0.0000))
	return VFP
subpax_surface_panel_11 = fex_subpax_surface_panel_11()

def fex_subpax_surface_panel_12():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(2753.3333, -500.0000, 0.0000))
	return VFP
subpax_surface_panel_12 = fex_subpax_surface_panel_12()

def fvol_pax_surface():
	V000 = subpax_surface_panel_0
	V001 = V000.fuse(subpax_surface_panel_1)
	V002 = V001.fuse(subpax_surface_panel_2)
	V003 = V002.fuse(subpax_surface_panel_3)
	V004 = V003.fuse(subpax_surface_panel_4)
	V005 = V004.fuse(subpax_surface_panel_5)
	V006 = V005.fuse(subpax_surface_panel_6)
	V007 = V006.fuse(subpax_surface_panel_7)
	V008 = V007.fuse(subpax_surface_panel_8)
	V009 = V008.fuse(subpax_surface_panel_9)
	V010 = V009.fuse(subpax_surface_panel_10)
	V011 = V010.fuse(subpax_surface_panel_11)
	V012 = V011.fuse(subpax_surface_panel_12)
	VFC = V012.removeSplitter()
	return VFC
pax_surface = fvol_pax_surface()


pax_surface.check()
#pax_surface.exportBrep(f"{outFileName}.brep")
#pax_surface.exportIges(f"{outFileName}.igs")
#pax_surface.exportStep(f"{outFileName}.stp")
pax_surface.exportStl(f"{outFileName}.stl")

