# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "lettreL"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_lettreL_face1_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(40.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.0000, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(10.0000, 10.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(10.0000, 60.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(0.0000, 60.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S005 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lettreL_face1_Fa0():
	FC000 = ctr_face_lettreL_face1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def lettreL_face1():
	FA000 = face_lettreL_face1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_lettreL():
	FIG = lettreL_face1()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_lettreL = fex_subpax_lettreL()

pax_lettreL = subpax_lettreL

pax_lettreL.check()
#pax_lettreL.exportBrep(f"{outFileName}.brep")
#pax_lettreL.exportIges(f"{outFileName}.igs")
#pax_lettreL.exportStep(f"{outFileName}.stp")
pax_lettreL.exportStl(f"{outFileName}.stl")

