# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "pencil_holder"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_pencil_holder_faceTop_Fa0_Ctr0():
	P000 = App.Vector(5.0000, 0.0000, 0)
	P001 = App.Vector(25.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(28.5355, 1.4645, 0)
	P003 = App.Vector(30.0000, 5.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(30.0000, 85.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(28.5355, 88.5355, 0)
	P006 = App.Vector(25.0000, 90.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(5.0000, 90.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(1.4645, 88.5355, 0)
	P009 = App.Vector(0.0000, 85.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(0.0000, 5.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(1.4645, 1.4645, 0)
	P012 = App.Vector(5.0000, 0.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pencil_holder_faceTop_Fa0_Ctr1():
	P000 = App.Vector(12.0000, 10.0000, 0)
	P001 = App.Vector(18.0000, 10.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 10.5858, 0)
	P003 = App.Vector(20.0000, 12.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(20.0000, 18.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(19.4142, 19.4142, 0)
	P006 = App.Vector(18.0000, 20.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(12.0000, 20.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(10.5858, 19.4142, 0)
	P009 = App.Vector(10.0000, 18.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(10.0000, 12.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(10.5858, 10.5858, 0)
	P012 = App.Vector(12.0000, 10.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pencil_holder_faceTop_Fa0_Ctr2():
	P000 = App.Vector(12.0000, 22.0000, 0)
	P001 = App.Vector(18.0000, 22.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 22.5858, 0)
	P003 = App.Vector(20.0000, 24.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(20.0000, 30.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(19.4142, 31.4142, 0)
	P006 = App.Vector(18.0000, 32.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(12.0000, 32.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(10.5858, 31.4142, 0)
	P009 = App.Vector(10.0000, 30.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(10.0000, 24.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(10.5858, 22.5858, 0)
	P012 = App.Vector(12.0000, 22.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pencil_holder_faceTop_Fa0_Ctr3():
	P000 = App.Vector(12.0000, 34.0000, 0)
	P001 = App.Vector(18.0000, 34.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 34.5858, 0)
	P003 = App.Vector(20.0000, 36.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(20.0000, 42.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(19.4142, 43.4142, 0)
	P006 = App.Vector(18.0000, 44.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(12.0000, 44.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(10.5858, 43.4142, 0)
	P009 = App.Vector(10.0000, 42.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(10.0000, 36.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(10.5858, 34.5858, 0)
	P012 = App.Vector(12.0000, 34.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pencil_holder_faceTop_Fa0_Ctr4():
	P000 = App.Vector(12.0000, 46.0000, 0)
	P001 = App.Vector(18.0000, 46.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 46.5858, 0)
	P003 = App.Vector(20.0000, 48.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(20.0000, 54.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(19.4142, 55.4142, 0)
	P006 = App.Vector(18.0000, 56.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(12.0000, 56.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(10.5858, 55.4142, 0)
	P009 = App.Vector(10.0000, 54.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(10.0000, 48.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(10.5858, 46.5858, 0)
	P012 = App.Vector(12.0000, 46.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pencil_holder_faceTop_Fa0_Ctr5():
	P000 = App.Vector(12.0000, 58.0000, 0)
	P001 = App.Vector(18.0000, 58.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 58.5858, 0)
	P003 = App.Vector(20.0000, 60.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(20.0000, 66.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(19.4142, 67.4142, 0)
	P006 = App.Vector(18.0000, 68.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(12.0000, 68.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(10.5858, 67.4142, 0)
	P009 = App.Vector(10.0000, 66.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(10.0000, 60.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(10.5858, 58.5858, 0)
	P012 = App.Vector(12.0000, 58.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pencil_holder_faceTop_Fa0_Ctr6():
	P000 = App.Vector(12.0000, 70.0000, 0)
	P001 = App.Vector(18.0000, 70.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 70.5858, 0)
	P003 = App.Vector(20.0000, 72.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(20.0000, 78.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(19.4142, 79.4142, 0)
	P006 = App.Vector(18.0000, 80.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(12.0000, 80.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(10.5858, 79.4142, 0)
	P009 = App.Vector(10.0000, 78.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(10.0000, 72.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(10.5858, 70.5858, 0)
	P012 = App.Vector(12.0000, 70.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pencil_holder_faceTop_Fa0():
	FC000 = ctr_face_pencil_holder_faceTop_Fa0_Ctr0()
	FC001 = ctr_face_pencil_holder_faceTop_Fa0_Ctr1()
	FC002 = ctr_face_pencil_holder_faceTop_Fa0_Ctr2()
	FC003 = ctr_face_pencil_holder_faceTop_Fa0_Ctr3()
	FC004 = ctr_face_pencil_holder_faceTop_Fa0_Ctr4()
	FC005 = ctr_face_pencil_holder_faceTop_Fa0_Ctr5()
	FC006 = ctr_face_pencil_holder_faceTop_Fa0_Ctr6()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006])
	rOneFace.check()
	return rOneFace

def pencil_holder_faceTop():
	FA000 = face_pencil_holder_faceTop_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pencil_holder_faceFace_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(30.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(30.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pencil_holder_faceFace_Fa0():
	FC000 = ctr_face_pencil_holder_faceFace_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pencil_holder_faceFace():
	FA000 = face_pencil_holder_faceFace_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pencil_holder_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(90.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(90.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pencil_holder_faceSide_Fa0():
	FC000 = ctr_face_pencil_holder_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pencil_holder_faceSide():
	FA000 = face_pencil_holder_faceSide_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_pencil_holder():
	FIG = pencil_holder_faceTop()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_pencil_holder = fex_subpax_pencil_holder()

pax_pencil_holder = subpax_pencil_holder

pax_pencil_holder.check()
#pax_pencil_holder.exportBrep(f"{outFileName}.brep")
#pax_pencil_holder.exportIges(f"{outFileName}.igs")
#pax_pencil_holder.exportStep(f"{outFileName}.stp")
pax_pencil_holder.exportStl(f"{outFileName}.stl")

