# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "spiral"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_spiral_faceTop_Fa0_Ctr0():
	P000 = App.Vector(-100.0000, 0.0000, 0)
	P001 = App.Vector(-102.5000, 2.5000, 0)
	P002 = App.Vector(-105.0000, 0.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-74.2462, -74.2462, 0)
	P004 = App.Vector(-0.0000, -105.0000, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(80.4334, -71.6834, 0)
	P006 = App.Vector(113.7500, 8.7500, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(77.8706, 95.3706, 0)
	P008 = App.Vector(-8.7500, 131.2500, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(-101.5578, 92.8078, 0)
	P010 = App.Vector(-140.0000, 0.0000, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(-98.9949, -98.9949, 0)
	P012 = App.Vector(-0.0000, -140.0000, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(105.1821, -96.4321, 0)
	P014 = App.Vector(148.7500, 8.7500, 0)
	S006 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(102.6193, 120.1193, 0)
	P016 = App.Vector(-8.7500, 166.2500, 0)
	S007 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-126.3065, 117.5565, 0)
	P018 = App.Vector(-175.0000, 0.0000, 0)
	S008 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-172.5000, -2.5000, 0)
	P020 = App.Vector(-170.0000, 0.0000, 0)
	S009 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-122.7710, 114.0210, 0)
	P022 = App.Vector(-8.7500, 161.2500, 0)
	S010 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(99.0838, 116.5838, 0)
	P024 = App.Vector(143.7500, 8.7500, 0)
	S011 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(101.6466, -92.8966, 0)
	P026 = App.Vector(-0.0000, -135.0000, 0)
	S012 = Part.Arc(P024, P025, P026)
	P027 = App.Vector(-95.4594, -95.4594, 0)
	P028 = App.Vector(-135.0000, 0.0000, 0)
	S013 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-98.0222, 89.2722, 0)
	P030 = App.Vector(-8.7500, 126.2500, 0)
	S014 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(74.3350, 91.8350, 0)
	P032 = App.Vector(108.7500, 8.7500, 0)
	S015 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(76.8979, -68.1479, 0)
	P034 = App.Vector(-0.0000, -100.0000, 0)
	S016 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-70.7107, -70.7107, 0)
	P036 = App.Vector(-100.0000, 0.0000, 0)
	S017 = Part.Arc(P034, P035, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceTop_Fa0():
	FC000 = ctr_face_spiral_faceTop_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def spiral_faceTop():
	FA000 = face_spiral_faceTop_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_spiral_faceSide_Fa0_Ctr0():
	P000 = App.Vector(-105.0000, 0.0000, 0)
	P001 = App.Vector(-100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-100.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-105.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-105.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa0():
	FC000 = ctr_face_spiral_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa1_Ctr0():
	P000 = App.Vector(108.7500, 0.0000, 0)
	P001 = App.Vector(113.7500, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(113.7500, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(108.7500, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(108.7500, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa1():
	FC000 = ctr_face_spiral_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa2_Ctr0():
	P000 = App.Vector(-140.0000, 0.0000, 0)
	P001 = App.Vector(-135.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-135.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-140.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-140.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa2():
	FC000 = ctr_face_spiral_faceSide_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa3_Ctr0():
	P000 = App.Vector(143.7500, 0.0000, 0)
	P001 = App.Vector(148.7500, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(148.7500, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(143.7500, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(143.7500, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa3():
	FC000 = ctr_face_spiral_faceSide_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa4_Ctr0():
	P000 = App.Vector(-175.0000, 0.0000, 0)
	P001 = App.Vector(-170.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-170.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-175.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-175.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa4():
	FC000 = ctr_face_spiral_faceSide_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def spiral_faceSide():
	FA000 = face_spiral_faceSide_Fa0()
	FA001 = face_spiral_faceSide_Fa1()
	FA002 = face_spiral_faceSide_Fa2()
	FA003 = face_spiral_faceSide_Fa3()
	FA004 = face_spiral_faceSide_Fa4()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004])
	rOneFig.check()
	return rOneFig

def fex_subpax_spiral():
	FIG = spiral_faceTop()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_spiral = fex_subpax_spiral()

pax_spiral = subpax_spiral

pax_spiral.check()
#pax_spiral.exportBrep(f"{outFileName}.brep")
#pax_spiral.exportIges(f"{outFileName}.igs")
#pax_spiral.exportStep(f"{outFileName}.stp")
pax_spiral.exportStl(f"{outFileName}.stl")

