# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "gear_wheel"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_gear_wheel_teethProfile_Fa0_Ctr0():
	P000 = App.Vector(104.3731, -3.4921, 0)
	P001 = App.Vector(104.9413, -3.5111, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(106.6850, -3.1552, 0)
	P003 = App.Vector(108.4003, -2.6809, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(110.5629, -1.9389, 0)
	P005 = App.Vector(112.6829, -1.0828, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(115.6656, 0.3322, 0)
	P007 = App.Vector(118.5498, 1.9383, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(121.7579, 3.9898, 0)
	P009 = App.Vector(124.8452, 6.2190, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(124.5292, 10.8387, 0)
	S005 = Part.LineSegment(P009, P010)
	P011 = App.Vector(121.1672, 12.6268, 0)
	P012 = App.Vector(117.7096, 14.2222, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(114.6335, 15.4207, 0)
	P014 = App.Vector(111.4859, 16.4164, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(109.2691, 16.9758, 0)
	P016 = App.Vector(107.0256, 17.4165, 0)
	S008 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(105.2617, 17.6527, 0)
	P018 = App.Vector(103.4858, 17.7679, 0)
	S009 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(102.9254, 17.6717, 0)
	S010 = Part.LineSegment(P018, P019)
	P020 = App.Vector(101.4611, 17.9899, 0)
	P021 = App.Vector(100.6288, 19.2359, 0)
	S011 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(99.9615, 22.4472, 0)
	S012 = Part.LineSegment(P021, P022)
	P023 = App.Vector(100.2285, 23.9217, 0)
	P024 = App.Vector(101.4448, 24.7969, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(101.9971, 24.9319, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(103.5801, 25.7451, 0)
	P027 = App.Vector(105.1038, 26.6645, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(106.9860, 27.9625, 0)
	P029 = App.Vector(108.7964, 29.3588, 0)
	S016 = Part.Arc(P027, P028, P029)
	P030 = App.Vector(111.2868, 31.5260, 0)
	P031 = App.Vector(113.6307, 33.8508, 0)
	S017 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(116.1664, 36.6917, 0)
	P033 = App.Vector(118.5377, 39.6712, 0)
	S018 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(116.9871, 44.0343, 0)
	S019 = Part.LineSegment(P033, P034)
	P035 = App.Vector(113.2673, 44.8490, 0)
	P036 = App.Vector(109.5075, 45.4525, 0)
	S020 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(106.2221, 45.7766, 0)
	P038 = App.Vector(102.9226, 45.8861, 0)
	S021 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(100.6371, 45.8267, 0)
	P040 = App.Vector(98.3579, 45.6458, 0)
	S022 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(96.5957, 45.3974, 0)
	P042 = App.Vector(94.8545, 45.0291, 0)
	S023 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(94.3409, 44.7853, 0)
	S024 = Part.LineSegment(P042, P043)
	P044 = App.Vector(92.8451, 44.6966, 0)
	P045 = App.Vector(91.7075, 45.6720, 0)
	S025 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(90.1985, 48.5841, 0)
	S026 = Part.LineSegment(P045, P046)
	P047 = App.Vector(90.0577, 50.0760, 0)
	P048 = App.Vector(90.9928, 51.2469, 0)
	S027 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(91.4882, 51.5259, 0)
	S028 = Part.LineSegment(P048, P049)
	P050 = App.Vector(92.7931, 52.7360, 0)
	P051 = App.Vector(94.0123, 54.0324, 0)
	S029 = Part.Arc(P049, P050, P051)
	P052 = App.Vector(95.4744, 55.7901, 0)
	P053 = App.Vector(96.8410, 57.6230, 0)
	S030 = Part.Arc(P051, P052, P053)
	P054 = App.Vector(98.6543, 60.3818, 0)
	P055 = App.Vector(100.2841, 63.2527, 0)
	S031 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(101.9593, 66.6724, 0)
	P057 = App.Vector(103.4389, 70.1812, 0)
	S032 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(100.7686, 73.9642, 0)
	S033 = Part.LineSegment(P057, P058)
	P059 = App.Vector(96.9669, 73.7451, 0)
	P060 = App.Vector(93.1837, 73.3118, 0)
	S034 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(89.9327, 72.7375, 0)
	P062 = App.Vector(86.7260, 71.9528, 0)
	S035 = Part.Arc(P060, P061, P062)
	P063 = App.Vector(84.5413, 71.2789, 0)
	P064 = App.Vector(82.3954, 70.4898, 0)
	S036 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(80.7656, 69.7751, 0)
	P066 = App.Vector(79.1883, 68.9508, 0)
	S037 = Part.Arc(P064, P065, P066)
	P067 = App.Vector(78.7596, 68.5774, 0)
	S038 = Part.LineSegment(P066, P067)
	P068 = App.Vector(77.3431, 68.0885, 0)
	P069 = App.Vector(75.9845, 68.7207, 0)
	S039 = Part.Arc(P067, P068, P069)
	P070 = App.Vector(73.7459, 71.1177, 0)
	S040 = Part.LineSegment(P069, P070)
	P071 = App.Vector(73.2078, 72.5163, 0)
	P072 = App.Vector(73.7923, 73.8961, 0)
	S041 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(74.1940, 74.2984, 0)
	S042 = Part.LineSegment(P072, P073)
	P074 = App.Vector(75.1241, 75.8156, 0)
	P075 = App.Vector(75.9483, 77.3930, 0)
	S043 = Part.Arc(P073, P074, P075)
	P076 = App.Vector(76.8820, 79.4799, 0)
	P077 = App.Vector(77.7034, 81.6136, 0)
	S044 = Part.Arc(P075, P076, P077)
	P078 = App.Vector(78.7051, 84.7593, 0)
	P079 = App.Vector(79.4999, 87.9635, 0)
	S045 = Part.Arc(P077, P078, P079)
	P080 = App.Vector(80.1904, 91.7083, 0)
	P081 = App.Vector(80.6684, 95.4861, 0)
	S046 = Part.Arc(P079, P080, P081)
	P082 = App.Vector(77.0765, 98.4084, 0)
	S047 = Part.LineSegment(P081, P082)
	P083 = App.Vector(73.4749, 97.1718, 0)
	P084 = App.Vector(69.9489, 95.7338, 0)
	S048 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(66.9734, 94.3037, 0)
	P086 = App.Vector(64.0974, 92.6829, 0)
	S049 = Part.Arc(P084, P085, P086)
	P087 = App.Vector(62.1754, 91.4446, 0)
	P088 = App.Vector(60.3221, 90.1058, 0)
	S050 = Part.Arc(P086, P087, P088)
	P089 = App.Vector(58.9454, 88.9780, 0)
	P090 = App.Vector(57.6491, 87.7586, 0)
	S051 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(57.3370, 87.2835, 0)
	S052 = Part.LineSegment(P090, P091)
	P092 = App.Vector(56.1050, 86.4305, 0)
	P093 = App.Vector(54.6262, 86.6727, 0)
	S053 = Part.Arc(P091, P092, P093)
	P094 = App.Vector(51.8238, 88.3769, 0)
	S054 = Part.LineSegment(P093, P094)
	P095 = App.Vector(50.9284, 89.5784, 0)
	P096 = App.Vector(51.1190, 91.0647, 0)
	S055 = Part.Arc(P094, P095, P096)
	P097 = App.Vector(51.3973, 91.5605, 0)
	S056 = Part.LineSegment(P096, P097)
	P098 = App.Vector(51.8835, 93.2724, 0)
	P099 = App.Vector(52.2516, 95.0136, 0)
	S057 = Part.Arc(P097, P098, P099)
	P100 = App.Vector(52.5876, 97.2751, 0)
	P101 = App.Vector(52.8029, 99.5513, 0)
	S058 = Part.Arc(P099, P100, P101)
	P102 = App.Vector(52.9188, 102.8506, 0)
	P103 = App.Vector(52.8196, 106.1504, 0)
	S059 = Part.Arc(P101, P102, P103)
	P104 = App.Vector(52.4741, 109.9426, 0)
	P105 = App.Vector(51.9152, 113.7093, 0)
	S060 = Part.Arc(P103, P104, P105)
	P106 = App.Vector(47.6680, 115.5541, 0)
	S061 = Part.LineSegment(P105, P106)
	P107 = App.Vector(44.5337, 113.3917, 0)
	P108 = App.Vector(41.5263, 111.0557, 0)
	S062 = Part.Arc(P106, P107, P108)
	P109 = App.Vector(39.0470, 108.8759, 0)
	P110 = App.Vector(36.7149, 106.5393, 0)
	S063 = Part.Arc(P108, P109, P110)
	P111 = App.Vector(35.1983, 104.8283, 0)
	P112 = App.Vector(33.7749, 103.0392, 0)
	S064 = Part.Arc(P110, P111, P112)
	P113 = App.Vector(32.7536, 101.5817, 0)
	P114 = App.Vector(31.8343, 100.0579, 0)
	S065 = Part.Arc(P112, P113, P114)
	P115 = App.Vector(31.6620, 99.5161, 0)
	S066 = Part.LineSegment(P114, P115)
	P116 = App.Vector(30.7058, 98.3623, 0)
	P117 = App.Vector(29.2165, 98.1966, 0)
	S067 = Part.Arc(P115, P116, P117)
	P118 = App.Vector(26.0583, 99.0815, 0)
	S068 = Part.LineSegment(P117, P118)
	P119 = App.Vector(24.8719, 99.9969, 0)
	P120 = App.Vector(24.6544, 101.4795, 0)
	S069 = Part.Arc(P118, P119, P120)
	P121 = App.Vector(24.7886, 102.0320, 0)
	S070 = Part.LineSegment(P120, P121)
	P122 = App.Vector(24.7949, 103.8116, 0)
	P123 = App.Vector(24.6796, 105.5876, 0)
	S071 = Part.Arc(P121, P122, P123)
	P124 = App.Vector(24.3930, 107.8559, 0)
	P125 = App.Vector(23.9862, 110.1057, 0)
	S072 = Part.Arc(P123, P124, P125)
	P126 = App.Vector(23.2076, 113.3139, 0)
	P127 = App.Vector(22.2219, 116.4646, 0)
	S073 = Part.Arc(P125, P126, P127)
	P128 = App.Vector(20.8661, 120.0230, 0)
	P129 = App.Vector(19.3116, 123.4992, 0)
	S074 = Part.Arc(P127, P128, P129)
	P130 = App.Vector(14.7242, 124.1298, 0)
	S075 = Part.LineSegment(P129, P130)
	P131 = App.Vector(12.2895, 121.2018, 0)
	P132 = App.Vector(10.0239, 118.1412, 0)
	S076 = Part.Arc(P130, P131, P132)
	P133 = App.Vector(8.2247, 115.3733, 0)
	P134 = App.Vector(6.6095, 112.4941, 0)
	S077 = Part.Arc(P132, P133, P134)
	P135 = App.Vector(5.6107, 110.4374, 0)
	P136 = App.Vector(4.7228, 108.3306, 0)
	S078 = Part.Arc(P134, P135, P136)
	P137 = App.Vector(4.1326, 106.6516, 0)
	P138 = App.Vector(3.6585, 104.9362, 0)
	S079 = Part.Arc(P136, P137, P138)
	P139 = App.Vector(3.6387, 104.3681, 0)
	S080 = Part.LineSegment(P138, P139)
	P140 = App.Vector(3.0293, 102.9991, 0)
	P141 = App.Vector(1.6399, 102.4378, 0)
	S081 = Part.Arc(P139, P140, P141)
	P142 = App.Vector(-1.6399, 102.4378, 0)
	S082 = Part.LineSegment(P141, P142)
	P143 = App.Vector(-3.0293, 102.9991, 0)
	P144 = App.Vector(-3.6387, 104.3681, 0)
	S083 = Part.Arc(P142, P143, P144)
	P145 = App.Vector(-3.6585, 104.9362, 0)
	S084 = Part.LineSegment(P144, P145)
	P146 = App.Vector(-4.1326, 106.6516, 0)
	P147 = App.Vector(-4.7228, 108.3306, 0)
	S085 = Part.Arc(P145, P146, P147)
	P148 = App.Vector(-5.6107, 110.4374, 0)
	P149 = App.Vector(-6.6095, 112.4941, 0)
	S086 = Part.Arc(P147, P148, P149)
	P150 = App.Vector(-8.2247, 115.3733, 0)
	P151 = App.Vector(-10.0239, 118.1412, 0)
	S087 = Part.Arc(P149, P150, P151)
	P152 = App.Vector(-12.2895, 121.2018, 0)
	P153 = App.Vector(-14.7242, 124.1298, 0)
	S088 = Part.Arc(P151, P152, P153)
	P154 = App.Vector(-19.3116, 123.4992, 0)
	S089 = Part.LineSegment(P153, P154)
	P155 = App.Vector(-20.8661, 120.0230, 0)
	P156 = App.Vector(-22.2219, 116.4646, 0)
	S090 = Part.Arc(P154, P155, P156)
	P157 = App.Vector(-23.2076, 113.3139, 0)
	P158 = App.Vector(-23.9862, 110.1057, 0)
	S091 = Part.Arc(P156, P157, P158)
	P159 = App.Vector(-24.3930, 107.8559, 0)
	P160 = App.Vector(-24.6796, 105.5876, 0)
	S092 = Part.Arc(P158, P159, P160)
	P161 = App.Vector(-24.7949, 103.8116, 0)
	P162 = App.Vector(-24.7886, 102.0320, 0)
	S093 = Part.Arc(P160, P161, P162)
	P163 = App.Vector(-24.6544, 101.4795, 0)
	S094 = Part.LineSegment(P162, P163)
	P164 = App.Vector(-24.8719, 99.9969, 0)
	P165 = App.Vector(-26.0583, 99.0815, 0)
	S095 = Part.Arc(P163, P164, P165)
	P166 = App.Vector(-29.2165, 98.1966, 0)
	S096 = Part.LineSegment(P165, P166)
	P167 = App.Vector(-30.7058, 98.3623, 0)
	P168 = App.Vector(-31.6620, 99.5161, 0)
	S097 = Part.Arc(P166, P167, P168)
	P169 = App.Vector(-31.8343, 100.0579, 0)
	S098 = Part.LineSegment(P168, P169)
	P170 = App.Vector(-32.7536, 101.5817, 0)
	P171 = App.Vector(-33.7749, 103.0392, 0)
	S099 = Part.Arc(P169, P170, P171)
	P172 = App.Vector(-35.1983, 104.8283, 0)
	P173 = App.Vector(-36.7149, 106.5393, 0)
	S100 = Part.Arc(P171, P172, P173)
	P174 = App.Vector(-39.0470, 108.8759, 0)
	P175 = App.Vector(-41.5263, 111.0557, 0)
	S101 = Part.Arc(P173, P174, P175)
	P176 = App.Vector(-44.5337, 113.3917, 0)
	P177 = App.Vector(-47.6680, 115.5541, 0)
	S102 = Part.Arc(P175, P176, P177)
	P178 = App.Vector(-51.9152, 113.7093, 0)
	S103 = Part.LineSegment(P177, P178)
	P179 = App.Vector(-52.4741, 109.9426, 0)
	P180 = App.Vector(-52.8196, 106.1504, 0)
	S104 = Part.Arc(P178, P179, P180)
	P181 = App.Vector(-52.9188, 102.8506, 0)
	P182 = App.Vector(-52.8029, 99.5513, 0)
	S105 = Part.Arc(P180, P181, P182)
	P183 = App.Vector(-52.5876, 97.2751, 0)
	P184 = App.Vector(-52.2516, 95.0136, 0)
	S106 = Part.Arc(P182, P183, P184)
	P185 = App.Vector(-51.8835, 93.2724, 0)
	P186 = App.Vector(-51.3973, 91.5605, 0)
	S107 = Part.Arc(P184, P185, P186)
	P187 = App.Vector(-51.1190, 91.0647, 0)
	S108 = Part.LineSegment(P186, P187)
	P188 = App.Vector(-50.9284, 89.5784, 0)
	P189 = App.Vector(-51.8238, 88.3769, 0)
	S109 = Part.Arc(P187, P188, P189)
	P190 = App.Vector(-54.6262, 86.6727, 0)
	S110 = Part.LineSegment(P189, P190)
	P191 = App.Vector(-56.1050, 86.4305, 0)
	P192 = App.Vector(-57.3370, 87.2835, 0)
	S111 = Part.Arc(P190, P191, P192)
	P193 = App.Vector(-57.6491, 87.7586, 0)
	S112 = Part.LineSegment(P192, P193)
	P194 = App.Vector(-58.9454, 88.9780, 0)
	P195 = App.Vector(-60.3221, 90.1058, 0)
	S113 = Part.Arc(P193, P194, P195)
	P196 = App.Vector(-62.1754, 91.4446, 0)
	P197 = App.Vector(-64.0974, 92.6829, 0)
	S114 = Part.Arc(P195, P196, P197)
	P198 = App.Vector(-66.9734, 94.3037, 0)
	P199 = App.Vector(-69.9489, 95.7338, 0)
	S115 = Part.Arc(P197, P198, P199)
	P200 = App.Vector(-73.4749, 97.1718, 0)
	P201 = App.Vector(-77.0765, 98.4084, 0)
	S116 = Part.Arc(P199, P200, P201)
	P202 = App.Vector(-80.6684, 95.4861, 0)
	S117 = Part.LineSegment(P201, P202)
	P203 = App.Vector(-80.1904, 91.7083, 0)
	P204 = App.Vector(-79.4999, 87.9635, 0)
	S118 = Part.Arc(P202, P203, P204)
	P205 = App.Vector(-78.7051, 84.7593, 0)
	P206 = App.Vector(-77.7034, 81.6136, 0)
	S119 = Part.Arc(P204, P205, P206)
	P207 = App.Vector(-76.8820, 79.4799, 0)
	P208 = App.Vector(-75.9483, 77.3930, 0)
	S120 = Part.Arc(P206, P207, P208)
	P209 = App.Vector(-75.1241, 75.8156, 0)
	P210 = App.Vector(-74.1940, 74.2984, 0)
	S121 = Part.Arc(P208, P209, P210)
	P211 = App.Vector(-73.7923, 73.8961, 0)
	S122 = Part.LineSegment(P210, P211)
	P212 = App.Vector(-73.2078, 72.5163, 0)
	P213 = App.Vector(-73.7459, 71.1177, 0)
	S123 = Part.Arc(P211, P212, P213)
	P214 = App.Vector(-75.9845, 68.7207, 0)
	S124 = Part.LineSegment(P213, P214)
	P215 = App.Vector(-77.3431, 68.0885, 0)
	P216 = App.Vector(-78.7596, 68.5774, 0)
	S125 = Part.Arc(P214, P215, P216)
	P217 = App.Vector(-79.1883, 68.9508, 0)
	S126 = Part.LineSegment(P216, P217)
	P218 = App.Vector(-80.7656, 69.7751, 0)
	P219 = App.Vector(-82.3954, 70.4898, 0)
	S127 = Part.Arc(P217, P218, P219)
	P220 = App.Vector(-84.5413, 71.2789, 0)
	P221 = App.Vector(-86.7260, 71.9528, 0)
	S128 = Part.Arc(P219, P220, P221)
	P222 = App.Vector(-89.9327, 72.7375, 0)
	P223 = App.Vector(-93.1837, 73.3118, 0)
	S129 = Part.Arc(P221, P222, P223)
	P224 = App.Vector(-96.9669, 73.7451, 0)
	P225 = App.Vector(-100.7686, 73.9642, 0)
	S130 = Part.Arc(P223, P224, P225)
	P226 = App.Vector(-103.4389, 70.1812, 0)
	S131 = Part.LineSegment(P225, P226)
	P227 = App.Vector(-101.9593, 66.6724, 0)
	P228 = App.Vector(-100.2841, 63.2527, 0)
	S132 = Part.Arc(P226, P227, P228)
	P229 = App.Vector(-98.6543, 60.3818, 0)
	P230 = App.Vector(-96.8410, 57.6230, 0)
	S133 = Part.Arc(P228, P229, P230)
	P231 = App.Vector(-95.4744, 55.7901, 0)
	P232 = App.Vector(-94.0123, 54.0324, 0)
	S134 = Part.Arc(P230, P231, P232)
	P233 = App.Vector(-92.7931, 52.7360, 0)
	P234 = App.Vector(-91.4882, 51.5259, 0)
	S135 = Part.Arc(P232, P233, P234)
	P235 = App.Vector(-90.9928, 51.2469, 0)
	S136 = Part.LineSegment(P234, P235)
	P236 = App.Vector(-90.0577, 50.0760, 0)
	P237 = App.Vector(-90.1985, 48.5841, 0)
	S137 = Part.Arc(P235, P236, P237)
	P238 = App.Vector(-91.7075, 45.6720, 0)
	S138 = Part.LineSegment(P237, P238)
	P239 = App.Vector(-92.8451, 44.6966, 0)
	P240 = App.Vector(-94.3409, 44.7853, 0)
	S139 = Part.Arc(P238, P239, P240)
	P241 = App.Vector(-94.8545, 45.0291, 0)
	S140 = Part.LineSegment(P240, P241)
	P242 = App.Vector(-96.5957, 45.3974, 0)
	P243 = App.Vector(-98.3579, 45.6458, 0)
	S141 = Part.Arc(P241, P242, P243)
	P244 = App.Vector(-100.6371, 45.8267, 0)
	P245 = App.Vector(-102.9226, 45.8861, 0)
	S142 = Part.Arc(P243, P244, P245)
	P246 = App.Vector(-106.2221, 45.7766, 0)
	P247 = App.Vector(-109.5075, 45.4525, 0)
	S143 = Part.Arc(P245, P246, P247)
	P248 = App.Vector(-113.2673, 44.8490, 0)
	P249 = App.Vector(-116.9871, 44.0343, 0)
	S144 = Part.Arc(P247, P248, P249)
	P250 = App.Vector(-118.5377, 39.6712, 0)
	S145 = Part.LineSegment(P249, P250)
	P251 = App.Vector(-116.1664, 36.6917, 0)
	P252 = App.Vector(-113.6307, 33.8508, 0)
	S146 = Part.Arc(P250, P251, P252)
	P253 = App.Vector(-111.2868, 31.5260, 0)
	P254 = App.Vector(-108.7964, 29.3588, 0)
	S147 = Part.Arc(P252, P253, P254)
	P255 = App.Vector(-106.9860, 27.9625, 0)
	P256 = App.Vector(-105.1038, 26.6645, 0)
	S148 = Part.Arc(P254, P255, P256)
	P257 = App.Vector(-103.5801, 25.7451, 0)
	P258 = App.Vector(-101.9971, 24.9319, 0)
	S149 = Part.Arc(P256, P257, P258)
	P259 = App.Vector(-101.4448, 24.7969, 0)
	S150 = Part.LineSegment(P258, P259)
	P260 = App.Vector(-100.2285, 23.9217, 0)
	P261 = App.Vector(-99.9615, 22.4472, 0)
	S151 = Part.Arc(P259, P260, P261)
	P262 = App.Vector(-100.6288, 19.2359, 0)
	S152 = Part.LineSegment(P261, P262)
	P263 = App.Vector(-101.4611, 17.9899, 0)
	P264 = App.Vector(-102.9254, 17.6717, 0)
	S153 = Part.Arc(P262, P263, P264)
	P265 = App.Vector(-103.4858, 17.7679, 0)
	S154 = Part.LineSegment(P264, P265)
	P266 = App.Vector(-105.2617, 17.6527, 0)
	P267 = App.Vector(-107.0256, 17.4165, 0)
	S155 = Part.Arc(P265, P266, P267)
	P268 = App.Vector(-109.2691, 16.9758, 0)
	P269 = App.Vector(-111.4859, 16.4164, 0)
	S156 = Part.Arc(P267, P268, P269)
	P270 = App.Vector(-114.6335, 15.4207, 0)
	P271 = App.Vector(-117.7096, 14.2222, 0)
	S157 = Part.Arc(P269, P270, P271)
	P272 = App.Vector(-121.1672, 12.6268, 0)
	P273 = App.Vector(-124.5292, 10.8387, 0)
	S158 = Part.Arc(P271, P272, P273)
	P274 = App.Vector(-124.8452, 6.2190, 0)
	S159 = Part.LineSegment(P273, P274)
	P275 = App.Vector(-121.7579, 3.9898, 0)
	P276 = App.Vector(-118.5498, 1.9383, 0)
	S160 = Part.Arc(P274, P275, P276)
	P277 = App.Vector(-115.6656, 0.3322, 0)
	P278 = App.Vector(-112.6829, -1.0828, 0)
	S161 = Part.Arc(P276, P277, P278)
	P279 = App.Vector(-110.5629, -1.9389, 0)
	P280 = App.Vector(-108.4003, -2.6809, 0)
	S162 = Part.Arc(P278, P279, P280)
	P281 = App.Vector(-106.6850, -3.1552, 0)
	P282 = App.Vector(-104.9413, -3.5111, 0)
	S163 = Part.Arc(P280, P281, P282)
	P283 = App.Vector(-104.3731, -3.4921, 0)
	S164 = Part.LineSegment(P282, P283)
	P284 = App.Vector(-102.9657, -4.0067, 0)
	P285 = App.Vector(-102.3109, -5.3545, 0)
	S165 = Part.Arc(P283, P284, P285)
	P286 = App.Vector(-102.0870, -8.6267, 0)
	S166 = Part.LineSegment(P285, P286)
	P287 = App.Vector(-102.5523, -10.0511, 0)
	P288 = App.Vector(-103.8765, -10.7526, 0)
	S167 = Part.Arc(P286, P287, P288)
	P289 = App.Vector(-104.4419, -10.8111, 0)
	S168 = Part.LineSegment(P288, P289)
	P290 = App.Vector(-106.1210, -11.4011, 0)
	P291 = App.Vector(-107.7557, -12.1045, 0)
	S169 = Part.Arc(P289, P290, P291)
	P292 = App.Vector(-109.7971, -13.1342, 0)
	P293 = App.Vector(-111.7808, -14.2709, 0)
	S170 = Part.Arc(P291, P292, P293)
	P294 = App.Vector(-114.5430, -16.0789, 0)
	P295 = App.Vector(-117.1817, -18.0628, 0)
	S171 = Part.Arc(P293, P294, P295)
	P296 = App.Vector(-120.0806, -20.5320, 0)
	P297 = App.Vector(-122.8356, -23.1608, 0)
	S172 = Part.Arc(P295, P296, P297)
	P298 = App.Vector(-121.8935, -27.6945, 0)
	S173 = Part.LineSegment(P297, P298)
	P299 = App.Vector(-118.3193, -29.0081, 0)
	P300 = App.Vector(-114.6766, -30.1179, 0)
	S174 = Part.Arc(P298, P299, P300)
	P301 = App.Vector(-111.4660, -30.8863, 0)
	P302 = App.Vector(-108.2121, -31.4441, 0)
	S175 = Part.Arc(P300, P301, P302)
	P303 = App.Vector(-105.9398, -31.6965, 0)
	P304 = App.Vector(-103.6572, -31.8276, 0)
	S176 = Part.Arc(P302, P303, P304)
	P305 = App.Vector(-101.8776, -31.8215, 0)
	P306 = App.Vector(-100.1025, -31.6937, 0)
	S177 = Part.Arc(P304, P305, P306)
	P307 = App.Vector(-99.5605, -31.5221, 0)
	S178 = Part.LineSegment(P306, P307)
	P308 = App.Vector(-98.0665, -31.6379, 0)
	P309 = App.Vector(-97.0723, -32.7591, 0)
	S179 = Part.Arc(P307, P308, P309)
	P310 = App.Vector(-95.9739, -35.8496, 0)
	S180 = Part.LineSegment(P309, P310)
	P311 = App.Vector(-96.0376, -37.3467, 0)
	P312 = App.Vector(-97.1234, -38.3794, 0)
	S181 = Part.Arc(P310, P311, P312)
	P313 = App.Vector(-97.6522, -38.5883, 0)
	S182 = Part.LineSegment(P312, P313)
	P314 = App.Vector(-99.1097, -39.6094, 0)
	P315 = App.Vector(-100.4941, -40.7278, 0)
	S183 = Part.Arc(P313, P314, P315)
	P316 = App.Vector(-102.1819, -42.2700, 0)
	P317 = App.Vector(-103.7854, -43.8998, 0)
	S184 = Part.Arc(P315, P316, P317)
	P318 = App.Vector(-105.9574, -46.3860, 0)
	P319 = App.Vector(-107.9630, -49.0082, 0)
	S185 = Part.Arc(P317, P318, P319)
	P320 = App.Vector(-110.0882, -52.1680, 0)
	P321 = App.Vector(-112.0318, -55.4426, 0)
	S186 = Part.Arc(P319, P320, P321)
	P322 = App.Vector(-109.9014, -59.5539, 0)
	S187 = Part.LineSegment(P321, P322)
	P323 = App.Vector(-106.1054, -59.8545, 0)
	P324 = App.Vector(-102.2984, -59.9404, 0)
	S188 = Part.Arc(P322, P323, P324)
	P325 = App.Vector(-98.9995, -59.8142, 0)
	P326 = App.Vector(-95.7158, -59.4734, 0)
	S189 = Part.Arc(P324, P325, P326)
	P327 = App.Vector(-93.4596, -59.1033, 0)
	P328 = App.Vector(-91.2264, -58.6137, 0)
	S190 = Part.Arc(P326, P327, P328)
	P329 = App.Vector(-89.5143, -58.1277, 0)
	P330 = App.Vector(-87.8396, -57.5258, 0)
	S191 = Part.Arc(P328, P329, P330)
	P331 = App.Vector(-87.3640, -57.2143, 0)
	S192 = Part.LineSegment(P330, P331)
	P332 = App.Vector(-85.8941, -56.9227, 0)
	P333 = App.Vector(-84.6343, -57.7341, 0)
	S193 = Part.Arc(P331, P332, P333)
	P334 = App.Vector(-82.7428, -60.4136, 0)
	S194 = Part.LineSegment(P333, P334)
	P335 = App.Vector(-82.4002, -61.8724, 0)
	P336 = App.Vector(-83.1672, -63.1597, 0)
	S195 = Part.Arc(P334, P335, P336)
	P337 = App.Vector(-83.6199, -63.5036, 0)
	S196 = Part.LineSegment(P336, P337)
	P338 = App.Vector(-84.7480, -64.8801, 0)
	P339 = App.Vector(-85.7792, -66.3305, 0)
	S197 = Part.Arc(P337, P338, P339)
	P340 = App.Vector(-86.9884, -68.2709, 0)
	P341 = App.Vector(-88.0927, -70.2728, 0)
	S198 = Part.Arc(P339, P340, P341)
	P342 = App.Vector(-89.5135, -73.2528, 0)
	P343 = App.Vector(-90.7372, -76.3189, 0)
	S199 = Part.Arc(P341, P342, P343)
	P344 = App.Vector(-91.9311, -79.9349, 0)
	P345 = App.Vector(-92.9191, -83.6124, 0)
	S200 = Part.Arc(P343, P344, P345)
	P346 = App.Vector(-89.7585, -86.9966, 0)
	S201 = Part.LineSegment(P345, P346)
	P347 = App.Vector(-86.0221, -86.2619, 0)
	P348 = App.Vector(-82.3331, -85.3174, 0)
	S202 = Part.Arc(P346, P347, P348)
	P349 = App.Vector(-79.1907, -84.3058, 0)
	P350 = App.Vector(-76.1207, -83.0918, 0)
	S203 = Part.Arc(P348, P349, P350)
	P351 = App.Vector(-74.0480, -82.1267, 0)
	P352 = App.Vector(-72.0296, -81.0527, 0)
	S204 = Part.Arc(P350, P351, P352)
	P353 = App.Vector(-70.5123, -80.1228, 0)
	P354 = App.Vector(-69.0620, -79.0914, 0)
	S205 = Part.Arc(P352, P353, P354)
	P355 = App.Vector(-68.6880, -78.6631, 0)
	S206 = Part.LineSegment(P354, P355)
	P356 = App.Vector(-67.3514, -77.9858, 0)
	P357 = App.Vector(-65.9194, -78.4272, 0)
	S207 = Part.Arc(P355, P356, P357)
	P358 = App.Vector(-63.3751, -80.4971, 0)
	S208 = Part.LineSegment(P357, P358)
	P359 = App.Vector(-62.6516, -81.8093, 0)
	P360 = App.Vector(-63.0428, -83.2558, 0)
	S209 = Part.Arc(P358, P359, P360)
	P361 = App.Vector(-63.3860, -83.7091, 0)
	S210 = Part.LineSegment(P360, P361)
	P362 = App.Vector(-64.1008, -85.3389, 0)
	P363 = App.Vector(-64.7026, -87.0137, 0)
	S211 = Part.Arc(P361, P362, P363)
	P364 = App.Vector(-65.3434, -89.2084, 0)
	P365 = App.Vector(-65.8666, -91.4341, 0)
	S212 = Part.Arc(P363, P364, P365)
	P366 = App.Vector(-66.4307, -94.6868, 0)
	P367 = App.Vector(-66.7818, -97.9694, 0)
	S213 = Part.Arc(P365, P366, P367)
	P368 = App.Vector(-66.9559, -101.7734, 0)
	P369 = App.Vector(-66.9151, -105.5811, 0)
	S214 = Part.Arc(P367, P368, P369)
	P370 = App.Vector(-62.9586, -107.9871, 0)
	S215 = Part.LineSegment(P369, P370)
	P371 = App.Vector(-59.5590, -106.2715, 0)
	P372 = App.Vector(-56.2616, -104.3669, 0)
	S216 = Part.Arc(P370, P371, P372)
	P373 = App.Vector(-53.5086, -102.5449, 0)
	P374 = App.Vector(-50.8800, -100.5476, 0)
	S217 = Part.Arc(P372, P373, P374)
	P375 = App.Vector(-49.1446, -99.0591, 0)
	P376 = App.Vector(-47.4908, -97.4804, 0)
	S218 = Part.Arc(P374, P375, P376)
	P377 = App.Vector(-46.2806, -96.1756, 0)
	P378 = App.Vector(-45.1624, -94.7911, 0)
	S219 = Part.Arc(P376, P377, P378)
	P379 = App.Vector(-44.9178, -94.2779, 0)
	S220 = Part.LineSegment(P378, P379)
	P380 = App.Vector(-43.8135, -93.2651, 0)
	P381 = App.Vector(-42.3155, -93.3037, 0)
	S221 = Part.Arc(P379, P380, P381)
	P382 = App.Vector(-39.3071, -94.6104, 0)
	S222 = Part.LineSegment(P381, P382)
	P383 = App.Vector(-38.2565, -95.6788, 0)
	P384 = App.Vector(-38.2429, -97.1772, 0)
	S223 = Part.Arc(P382, P383, P384)
	P385 = App.Vector(-38.4511, -97.7063, 0)
	S224 = Part.LineSegment(P384, P385)
	P386 = App.Vector(-38.6996, -99.4685, 0)
	P387 = App.Vector(-38.8272, -101.2436, 0)
	S225 = Part.Arc(P385, P386, P387)
	P388 = App.Vector(-38.8522, -103.5298, 0)
	P389 = App.Vector(-38.7555, -105.8140, 0)
	S226 = Part.Arc(P387, P388, P389)
	P390 = App.Vector(-38.4211, -109.0984, 0)
	P391 = App.Vector(-37.8735, -112.3540, 0)
	S227 = Part.Arc(P389, P390, P391)
	P392 = App.Vector(-37.0149, -116.0638, 0)
	P393 = App.Vector(-35.9482, -119.7194, 0)
	S228 = Part.Arc(P391, P392, P393)
	P394 = App.Vector(-31.4894, -120.9687, 0)
	S229 = Part.LineSegment(P393, P394)
	P395 = App.Vector(-28.6787, -118.3995, 0)
	P396 = App.Vector(-26.0175, -115.6759, 0)
	S230 = Part.Arc(P394, P395, P396)
	P397 = App.Vector(-23.8581, -113.1787, 0)
	P398 = App.Vector(-21.8658, -110.5463, 0)
	S231 = Part.Arc(P396, P397, P398)
	P399 = App.Vector(-20.5964, -108.6448, 0)
	P400 = App.Vector(-19.4298, -106.6785, 0)
	S232 = Part.Arc(P398, P399, P400)
	P401 = App.Vector(-18.6165, -105.0955, 0)
	P402 = App.Vector(-17.9133, -103.4607, 0)
	S233 = Part.Arc(P400, P401, P402)
	P403 = App.Vector(-17.8163, -102.9005, 0)
	S234 = Part.LineSegment(P402, P403)
	P404 = App.Vector(-17.0261, -101.6273, 0)
	P405 = App.Vector(-15.5733, -101.2603, 0)
	S235 = Part.Arc(P403, P404, P405)
	P406 = App.Vector(-12.3239, -101.7070, 0)
	S236 = Part.LineSegment(P405, P406)
	P407 = App.Vector(-11.0240, -102.4523, 0)
	P408 = App.Vector(-10.6066, -103.8915, 0)
	S237 = Part.Arc(P406, P407, P408)
	P409 = App.Vector(-10.6644, -104.4570, 0)
	S238 = Part.LineSegment(P408, P409)
	P410 = App.Vector(-10.4283, -106.2210, 0)
	P411 = App.Vector(-10.0722, -107.9646, 0)
	S239 = Part.Arc(P409, P410, P411)
	P412 = App.Vector(-9.4794, -110.1728, 0)
	P413 = App.Vector(-8.7700, -112.3463, 0)
	S240 = Part.Arc(P411, P412, P413)
	P414 = App.Vector(-7.5619, -115.4186, 0)
	P415 = App.Vector(-6.1563, -118.4057, 0)
	S241 = Part.Arc(P413, P414, P415)
	P416 = App.Vector(-4.3286, -121.7464, 0)
	P417 = App.Vector(-2.3153, -124.9786, 0)
	S242 = Part.Arc(P415, P416, P417)
	P418 = App.Vector(2.3153, -124.9786, 0)
	S243 = Part.LineSegment(P417, P418)
	P419 = App.Vector(4.3286, -121.7464, 0)
	P420 = App.Vector(6.1563, -118.4057, 0)
	S244 = Part.Arc(P418, P419, P420)
	P421 = App.Vector(7.5619, -115.4186, 0)
	P422 = App.Vector(8.7700, -112.3463, 0)
	S245 = Part.Arc(P420, P421, P422)
	P423 = App.Vector(9.4794, -110.1728, 0)
	P424 = App.Vector(10.0722, -107.9646, 0)
	S246 = Part.Arc(P422, P423, P424)
	P425 = App.Vector(10.4283, -106.2210, 0)
	P426 = App.Vector(10.6644, -104.4570, 0)
	S247 = Part.Arc(P424, P425, P426)
	P427 = App.Vector(10.6066, -103.8915, 0)
	S248 = Part.LineSegment(P426, P427)
	P428 = App.Vector(11.0240, -102.4523, 0)
	P429 = App.Vector(12.3239, -101.7070, 0)
	S249 = Part.Arc(P427, P428, P429)
	P430 = App.Vector(15.5733, -101.2603, 0)
	S250 = Part.LineSegment(P429, P430)
	P431 = App.Vector(17.0261, -101.6273, 0)
	P432 = App.Vector(17.8163, -102.9005, 0)
	S251 = Part.Arc(P430, P431, P432)
	P433 = App.Vector(17.9133, -103.4607, 0)
	S252 = Part.LineSegment(P432, P433)
	P434 = App.Vector(18.6165, -105.0955, 0)
	P435 = App.Vector(19.4298, -106.6785, 0)
	S253 = Part.Arc(P433, P434, P435)
	P436 = App.Vector(20.5964, -108.6448, 0)
	P437 = App.Vector(21.8658, -110.5463, 0)
	S254 = Part.Arc(P435, P436, P437)
	P438 = App.Vector(23.8581, -113.1787, 0)
	P439 = App.Vector(26.0175, -115.6759, 0)
	S255 = Part.Arc(P437, P438, P439)
	P440 = App.Vector(28.6787, -118.3995, 0)
	P441 = App.Vector(31.4894, -120.9687, 0)
	S256 = Part.Arc(P439, P440, P441)
	P442 = App.Vector(35.9482, -119.7194, 0)
	S257 = Part.LineSegment(P441, P442)
	P443 = App.Vector(37.0149, -116.0638, 0)
	P444 = App.Vector(37.8735, -112.3540, 0)
	S258 = Part.Arc(P442, P443, P444)
	P445 = App.Vector(38.4211, -109.0984, 0)
	P446 = App.Vector(38.7555, -105.8140, 0)
	S259 = Part.Arc(P444, P445, P446)
	P447 = App.Vector(38.8522, -103.5298, 0)
	P448 = App.Vector(38.8272, -101.2436, 0)
	S260 = Part.Arc(P446, P447, P448)
	P449 = App.Vector(38.6996, -99.4685, 0)
	P450 = App.Vector(38.4511, -97.7063, 0)
	S261 = Part.Arc(P448, P449, P450)
	P451 = App.Vector(38.2429, -97.1772, 0)
	S262 = Part.LineSegment(P450, P451)
	P452 = App.Vector(38.2565, -95.6788, 0)
	P453 = App.Vector(39.3071, -94.6104, 0)
	S263 = Part.Arc(P451, P452, P453)
	P454 = App.Vector(42.3155, -93.3037, 0)
	S264 = Part.LineSegment(P453, P454)
	P455 = App.Vector(43.8135, -93.2651, 0)
	P456 = App.Vector(44.9178, -94.2779, 0)
	S265 = Part.Arc(P454, P455, P456)
	P457 = App.Vector(45.1624, -94.7911, 0)
	S266 = Part.LineSegment(P456, P457)
	P458 = App.Vector(46.2806, -96.1756, 0)
	P459 = App.Vector(47.4908, -97.4804, 0)
	S267 = Part.Arc(P457, P458, P459)
	P460 = App.Vector(49.1446, -99.0591, 0)
	P461 = App.Vector(50.8800, -100.5476, 0)
	S268 = Part.Arc(P459, P460, P461)
	P462 = App.Vector(53.5086, -102.5449, 0)
	P463 = App.Vector(56.2616, -104.3669, 0)
	S269 = Part.Arc(P461, P462, P463)
	P464 = App.Vector(59.5590, -106.2715, 0)
	P465 = App.Vector(62.9586, -107.9871, 0)
	S270 = Part.Arc(P463, P464, P465)
	P466 = App.Vector(66.9151, -105.5811, 0)
	S271 = Part.LineSegment(P465, P466)
	P467 = App.Vector(66.9559, -101.7734, 0)
	P468 = App.Vector(66.7818, -97.9694, 0)
	S272 = Part.Arc(P466, P467, P468)
	P469 = App.Vector(66.4307, -94.6868, 0)
	P470 = App.Vector(65.8666, -91.4341, 0)
	S273 = Part.Arc(P468, P469, P470)
	P471 = App.Vector(65.3434, -89.2084, 0)
	P472 = App.Vector(64.7026, -87.0137, 0)
	S274 = Part.Arc(P470, P471, P472)
	P473 = App.Vector(64.1008, -85.3389, 0)
	P474 = App.Vector(63.3860, -83.7091, 0)
	S275 = Part.Arc(P472, P473, P474)
	P475 = App.Vector(63.0428, -83.2558, 0)
	S276 = Part.LineSegment(P474, P475)
	P476 = App.Vector(62.6516, -81.8093, 0)
	P477 = App.Vector(63.3751, -80.4971, 0)
	S277 = Part.Arc(P475, P476, P477)
	P478 = App.Vector(65.9194, -78.4272, 0)
	S278 = Part.LineSegment(P477, P478)
	P479 = App.Vector(67.3514, -77.9858, 0)
	P480 = App.Vector(68.6880, -78.6631, 0)
	S279 = Part.Arc(P478, P479, P480)
	P481 = App.Vector(69.0620, -79.0914, 0)
	S280 = Part.LineSegment(P480, P481)
	P482 = App.Vector(70.5123, -80.1228, 0)
	P483 = App.Vector(72.0296, -81.0527, 0)
	S281 = Part.Arc(P481, P482, P483)
	P484 = App.Vector(74.0480, -82.1267, 0)
	P485 = App.Vector(76.1207, -83.0918, 0)
	S282 = Part.Arc(P483, P484, P485)
	P486 = App.Vector(79.1907, -84.3058, 0)
	P487 = App.Vector(82.3331, -85.3174, 0)
	S283 = Part.Arc(P485, P486, P487)
	P488 = App.Vector(86.0221, -86.2619, 0)
	P489 = App.Vector(89.7585, -86.9966, 0)
	S284 = Part.Arc(P487, P488, P489)
	P490 = App.Vector(92.9191, -83.6124, 0)
	S285 = Part.LineSegment(P489, P490)
	P491 = App.Vector(91.9311, -79.9349, 0)
	P492 = App.Vector(90.7372, -76.3189, 0)
	S286 = Part.Arc(P490, P491, P492)
	P493 = App.Vector(89.5135, -73.2528, 0)
	P494 = App.Vector(88.0927, -70.2728, 0)
	S287 = Part.Arc(P492, P493, P494)
	P495 = App.Vector(86.9884, -68.2709, 0)
	P496 = App.Vector(85.7792, -66.3305, 0)
	S288 = Part.Arc(P494, P495, P496)
	P497 = App.Vector(84.7480, -64.8801, 0)
	P498 = App.Vector(83.6199, -63.5036, 0)
	S289 = Part.Arc(P496, P497, P498)
	P499 = App.Vector(83.1672, -63.1597, 0)
	S290 = Part.LineSegment(P498, P499)
	P500 = App.Vector(82.4002, -61.8724, 0)
	P501 = App.Vector(82.7428, -60.4136, 0)
	S291 = Part.Arc(P499, P500, P501)
	P502 = App.Vector(84.6343, -57.7341, 0)
	S292 = Part.LineSegment(P501, P502)
	P503 = App.Vector(85.8941, -56.9227, 0)
	P504 = App.Vector(87.3640, -57.2143, 0)
	S293 = Part.Arc(P502, P503, P504)
	P505 = App.Vector(87.8396, -57.5258, 0)
	S294 = Part.LineSegment(P504, P505)
	P506 = App.Vector(89.5143, -58.1277, 0)
	P507 = App.Vector(91.2264, -58.6137, 0)
	S295 = Part.Arc(P505, P506, P507)
	P508 = App.Vector(93.4596, -59.1033, 0)
	P509 = App.Vector(95.7158, -59.4734, 0)
	S296 = Part.Arc(P507, P508, P509)
	P510 = App.Vector(98.9995, -59.8142, 0)
	P511 = App.Vector(102.2984, -59.9404, 0)
	S297 = Part.Arc(P509, P510, P511)
	P512 = App.Vector(106.1054, -59.8545, 0)
	P513 = App.Vector(109.9014, -59.5539, 0)
	S298 = Part.Arc(P511, P512, P513)
	P514 = App.Vector(112.0318, -55.4426, 0)
	S299 = Part.LineSegment(P513, P514)
	P515 = App.Vector(110.0882, -52.1680, 0)
	P516 = App.Vector(107.9630, -49.0082, 0)
	S300 = Part.Arc(P514, P515, P516)
	P517 = App.Vector(105.9574, -46.3860, 0)
	P518 = App.Vector(103.7854, -43.8998, 0)
	S301 = Part.Arc(P516, P517, P518)
	P519 = App.Vector(102.1819, -42.2700, 0)
	P520 = App.Vector(100.4941, -40.7278, 0)
	S302 = Part.Arc(P518, P519, P520)
	P521 = App.Vector(99.1097, -39.6094, 0)
	P522 = App.Vector(97.6522, -38.5883, 0)
	S303 = Part.Arc(P520, P521, P522)
	P523 = App.Vector(97.1234, -38.3794, 0)
	S304 = Part.LineSegment(P522, P523)
	P524 = App.Vector(96.0376, -37.3467, 0)
	P525 = App.Vector(95.9739, -35.8496, 0)
	S305 = Part.Arc(P523, P524, P525)
	P526 = App.Vector(97.0723, -32.7591, 0)
	S306 = Part.LineSegment(P525, P526)
	P527 = App.Vector(98.0665, -31.6379, 0)
	P528 = App.Vector(99.5605, -31.5221, 0)
	S307 = Part.Arc(P526, P527, P528)
	P529 = App.Vector(100.1025, -31.6937, 0)
	S308 = Part.LineSegment(P528, P529)
	P530 = App.Vector(101.8776, -31.8215, 0)
	P531 = App.Vector(103.6572, -31.8276, 0)
	S309 = Part.Arc(P529, P530, P531)
	P532 = App.Vector(105.9398, -31.6965, 0)
	P533 = App.Vector(108.2121, -31.4441, 0)
	S310 = Part.Arc(P531, P532, P533)
	P534 = App.Vector(111.4660, -30.8863, 0)
	P535 = App.Vector(114.6766, -30.1179, 0)
	S311 = Part.Arc(P533, P534, P535)
	P536 = App.Vector(118.3193, -29.0081, 0)
	P537 = App.Vector(121.8935, -27.6945, 0)
	S312 = Part.Arc(P535, P536, P537)
	P538 = App.Vector(122.8356, -23.1608, 0)
	S313 = Part.LineSegment(P537, P538)
	P539 = App.Vector(120.0806, -20.5320, 0)
	P540 = App.Vector(117.1817, -18.0628, 0)
	S314 = Part.Arc(P538, P539, P540)
	P541 = App.Vector(114.5430, -16.0789, 0)
	P542 = App.Vector(111.7808, -14.2709, 0)
	S315 = Part.Arc(P540, P541, P542)
	P543 = App.Vector(109.7971, -13.1342, 0)
	P544 = App.Vector(107.7557, -12.1045, 0)
	S316 = Part.Arc(P542, P543, P544)
	P545 = App.Vector(106.1210, -11.4011, 0)
	P546 = App.Vector(104.4419, -10.8111, 0)
	S317 = Part.Arc(P544, P545, P546)
	P547 = App.Vector(103.8765, -10.7526, 0)
	S318 = Part.LineSegment(P546, P547)
	P548 = App.Vector(102.5523, -10.0511, 0)
	P549 = App.Vector(102.0870, -8.6267, 0)
	S319 = Part.Arc(P547, P548, P549)
	P550 = App.Vector(102.3109, -5.3545, 0)
	S320 = Part.LineSegment(P549, P550)
	P551 = App.Vector(102.9657, -4.0067, 0)
	P552 = App.Vector(104.3731, -3.4921, 0)
	S321 = Part.Arc(P550, P551, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063, S064, S065, S066, S067, S068, S069, S070, S071, S072, S073, S074, S075, S076, S077, S078, S079, S080, S081, S082, S083, S084, S085, S086, S087, S088, S089, S090, S091, S092, S093, S094, S095, S096, S097, S098, S099, S100, S101, S102, S103, S104, S105, S106, S107, S108, S109, S110, S111, S112, S113, S114, S115, S116, S117, S118, S119, S120, S121, S122, S123, S124, S125, S126, S127, S128, S129, S130, S131, S132, S133, S134, S135, S136, S137, S138, S139, S140, S141, S142, S143, S144, S145, S146, S147, S148, S149, S150, S151, S152, S153, S154, S155, S156, S157, S158, S159, S160, S161, S162, S163, S164, S165, S166, S167, S168, S169, S170, S171, S172, S173, S174, S175, S176, S177, S178, S179, S180, S181, S182, S183, S184, S185, S186, S187, S188, S189, S190, S191, S192, S193, S194, S195, S196, S197, S198, S199, S200, S201, S202, S203, S204, S205, S206, S207, S208, S209, S210, S211, S212, S213, S214, S215, S216, S217, S218, S219, S220, S221, S222, S223, S224, S225, S226, S227, S228, S229, S230, S231, S232, S233, S234, S235, S236, S237, S238, S239, S240, S241, S242, S243, S244, S245, S246, S247, S248, S249, S250, S251, S252, S253, S254, S255, S256, S257, S258, S259, S260, S261, S262, S263, S264, S265, S266, S267, S268, S269, S270, S271, S272, S273, S274, S275, S276, S277, S278, S279, S280, S281, S282, S283, S284, S285, S286, S287, S288, S289, S290, S291, S292, S293, S294, S295, S296, S297, S298, S299, S300, S301, S302, S303, S304, S305, S306, S307, S308, S309, S310, S311, S312, S313, S314, S315, S316, S317, S318, S319, S320, S321])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_gear_wheel_teethProfile_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_gear_wheel_teethProfile_Fa0_Ctr2():
	P000 = App.Vector(90.9582, 16.8182, 0)
	P001 = App.Vector(74.8341, 54.3701, 0)
	P002 = App.Vector(44.1027, 81.3093, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(35.6273, 81.8064, 0)
	P004 = App.Vector(29.8243, 75.6093, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(15.2072, 30.6226, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(15.0604, 24.9372, 0)
	P007 = App.Vector(18.0373, 20.0912, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(21.8435, 15.8702, 0)
	P009 = App.Vector(24.6817, 10.9459, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(28.3706, 6.6173, 0)
	P011 = App.Vector(33.8231, 5.0000, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(81.1249, 5.0000, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(88.8120, 8.6040, 0)
	P014 = App.Vector(90.9582, 16.8182, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_gear_wheel_teethProfile_Fa0_Ctr3():
	P000 = App.Vector(12.1126, 91.7035, 0)
	P001 = App.Vector(-28.5841, 87.9727, 0)
	P002 = App.Vector(-63.7013, 67.0701, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-66.7931, 59.1631, 0)
	P004 = App.Vector(-62.6925, 51.7291, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(-24.4245, 23.9258, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-19.0627, 22.0293, 0)
	P007 = App.Vector(-13.5340, 23.3630, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-8.3435, 25.6785, 0)
	P009 = App.Vector(-2.7831, 26.8562, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(2.4736, 29.0269, 0)
	P011 = App.Vector(5.6966, 33.7127, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(20.3137, 78.6995, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(19.2615, 87.1240, 0)
	P014 = App.Vector(12.1126, 91.7035, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_gear_wheel_teethProfile_Fa0_Ctr4():
	P000 = App.Vector(-83.4722, 39.8577, 0)
	P001 = App.Vector(-92.5000, 0.0000, 0)
	P002 = App.Vector(-83.4722, -39.8577, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-76.9077, -45.2416, 0)
	P004 = App.Vector(-68.5704, -43.6389, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(-30.3024, -15.8356, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-26.8418, -11.3223, 0)
	P007 = App.Vector(-26.4018, -5.6521, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-27.0000, -0.0000, 0)
	P009 = App.Vector(-26.4018, 5.6521, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-26.8418, 11.3223, 0)
	P011 = App.Vector(-30.3024, 15.8356, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-68.5704, 43.6389, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(-76.9077, 45.2416, 0)
	P014 = App.Vector(-83.4722, 39.8577, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_gear_wheel_teethProfile_Fa0_Ctr5():
	P000 = App.Vector(-63.7013, -67.0701, 0)
	P001 = App.Vector(-28.5841, -87.9727, 0)
	P002 = App.Vector(12.1126, -91.7035, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(19.2615, -87.1240, 0)
	P004 = App.Vector(20.3137, -78.6995, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(5.6966, -33.7127, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(2.4736, -29.0269, 0)
	P007 = App.Vector(-2.7831, -26.8562, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-8.3435, -25.6785, 0)
	P009 = App.Vector(-13.5340, -23.3630, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-19.0627, -22.0293, 0)
	P011 = App.Vector(-24.4245, -23.9258, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-62.6925, -51.7291, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(-66.7931, -59.1631, 0)
	P014 = App.Vector(-63.7013, -67.0701, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_gear_wheel_teethProfile_Fa0_Ctr6():
	P000 = App.Vector(44.1027, -81.3093, 0)
	P001 = App.Vector(74.8341, -54.3701, 0)
	P002 = App.Vector(90.9582, -16.8182, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(88.8120, -8.6040, 0)
	P004 = App.Vector(81.1249, -5.0000, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(33.8231, -5.0000, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(28.3706, -6.6173, 0)
	P007 = App.Vector(24.6817, -10.9459, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(21.8435, -15.8702, 0)
	P009 = App.Vector(18.0373, -20.0912, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(15.0604, -24.9372, 0)
	P011 = App.Vector(15.2072, -30.6226, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(29.8243, -75.6093, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(35.6273, -81.8064, 0)
	P014 = App.Vector(44.1027, -81.3093, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_gear_wheel_teethProfile_Fa0():
	FC000 = ctr_face_gear_wheel_teethProfile_Fa0_Ctr0()
	FC001 = ctr_face_gear_wheel_teethProfile_Fa0_Ctr1()
	FC002 = ctr_face_gear_wheel_teethProfile_Fa0_Ctr2()
	FC003 = ctr_face_gear_wheel_teethProfile_Fa0_Ctr3()
	FC004 = ctr_face_gear_wheel_teethProfile_Fa0_Ctr4()
	FC005 = ctr_face_gear_wheel_teethProfile_Fa0_Ctr5()
	FC006 = ctr_face_gear_wheel_teethProfile_Fa0_Ctr6()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006])
	rOneFace.check()
	return rOneFace

def gear_wheel_teethProfile():
	FA000 = face_gear_wheel_teethProfile_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_gear_wheel_axisProfile_Fa0_Ctr0():
	P000 = App.Vector(0.0000, -20.0000, 0)
	P001 = App.Vector(0.0000, 20.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(126.0000, 20.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(126.0000, -20.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, -20.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_gear_wheel_axisProfile_Fa0():
	FC000 = ctr_face_gear_wheel_axisProfile_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def gear_wheel_axisProfile():
	FA000 = face_gear_wheel_axisProfile_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_gear_wheel_teethProfile():
	FIG = gear_wheel_teethProfile()
	VEX = FIG.extrude(App.Vector(0, 0, 152))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, -76.0000))
	return VFP
subpax_gear_wheel_teethProfile = fex_subpax_gear_wheel_teethProfile()

def fex_subpax_gear_wheel_axisProfile():
	FIG = gear_wheel_axisProfile()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_gear_wheel_axisProfile = fex_subpax_gear_wheel_axisProfile()

def fvol_pax_gear_wheel():
	V000 = subpax_gear_wheel_teethProfile
	V001 = V000.common(subpax_gear_wheel_axisProfile)
	VFC = V001.removeSplitter()
	return VFC
pax_gear_wheel = fvol_pax_gear_wheel()


pax_gear_wheel.check()
#pax_gear_wheel.exportBrep(f"{outFileName}.brep")
#pax_gear_wheel.exportIges(f"{outFileName}.igs")
#pax_gear_wheel.exportStep(f"{outFileName}.stp")
pax_gear_wheel.exportStl(f"{outFileName}.stl")

