# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "spiral"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_spiral_faceTop_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(-5.0000, 5.0000, 0)
	P002 = App.Vector(-10.0000, 0.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-7.0711, -7.0711, 0)
	P004 = App.Vector(-0.0000, -10.0000, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(14.1421, -4.1421, 0)
	P006 = App.Vector(20.0000, 10.0000, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(11.2132, 31.2132, 0)
	P008 = App.Vector(-10.0000, 40.0000, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(-38.2843, 28.2843, 0)
	P010 = App.Vector(-50.0000, 0.0000, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(-35.3553, -35.3553, 0)
	P012 = App.Vector(-0.0000, -50.0000, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(42.4264, -32.4264, 0)
	P014 = App.Vector(60.0000, 10.0000, 0)
	S006 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(39.4975, 59.4975, 0)
	P016 = App.Vector(-10.0000, 80.0000, 0)
	S007 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-66.5685, 56.5685, 0)
	P018 = App.Vector(-90.0000, 0.0000, 0)
	S008 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-63.6396, -63.6396, 0)
	P020 = App.Vector(-0.0000, -90.0000, 0)
	S009 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(70.7107, -60.7107, 0)
	P022 = App.Vector(100.0000, 10.0000, 0)
	S010 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(67.7817, 87.7817, 0)
	P024 = App.Vector(-10.0000, 120.0000, 0)
	S011 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-94.8528, 84.8528, 0)
	P026 = App.Vector(-130.0000, -0.0000, 0)
	S012 = Part.Arc(P024, P025, P026)
	P027 = App.Vector(-91.9239, -91.9239, 0)
	P028 = App.Vector(0.0000, -130.0000, 0)
	S013 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(98.9949, -88.9949, 0)
	P030 = App.Vector(140.0000, 10.0000, 0)
	S014 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(96.0660, 116.0660, 0)
	P032 = App.Vector(-10.0000, 160.0000, 0)
	S015 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(-123.1371, 113.1371, 0)
	P034 = App.Vector(-170.0000, -0.0000, 0)
	S016 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-120.2082, -120.2082, 0)
	P036 = App.Vector(0.0000, -170.0000, 0)
	S017 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(127.2792, -117.2792, 0)
	P038 = App.Vector(180.0000, 10.0000, 0)
	S018 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(124.3503, 144.3503, 0)
	P040 = App.Vector(-10.0000, 200.0000, 0)
	S019 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-151.4214, 141.4214, 0)
	P042 = App.Vector(-210.0000, -0.0000, 0)
	S020 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-148.4924, -148.4924, 0)
	P044 = App.Vector(0.0000, -210.0000, 0)
	S021 = Part.Arc(P042, P043, P044)
	P045 = App.Vector(155.5635, -145.5635, 0)
	P046 = App.Vector(220.0000, 10.0000, 0)
	S022 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(152.6346, 172.6346, 0)
	P048 = App.Vector(-10.0000, 240.0000, 0)
	S023 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(-179.7056, 169.7056, 0)
	P050 = App.Vector(-250.0000, -0.0000, 0)
	S024 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(-176.7767, -176.7767, 0)
	P052 = App.Vector(0.0000, -250.0000, 0)
	S025 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(183.8478, -173.8478, 0)
	P054 = App.Vector(260.0000, 10.0000, 0)
	S026 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(180.9188, 200.9188, 0)
	P056 = App.Vector(-10.0000, 280.0000, 0)
	S027 = Part.Arc(P054, P055, P056)
	P057 = App.Vector(-207.9899, 197.9899, 0)
	P058 = App.Vector(-290.0000, -0.0000, 0)
	S028 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(-205.0610, -205.0610, 0)
	P060 = App.Vector(0.0000, -290.0000, 0)
	S029 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(212.1320, -202.1320, 0)
	P062 = App.Vector(300.0000, 10.0000, 0)
	S030 = Part.Arc(P060, P061, P062)
	P063 = App.Vector(295.0000, 15.0000, 0)
	P064 = App.Vector(290.0000, 10.0000, 0)
	S031 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(205.0610, -195.0610, 0)
	P066 = App.Vector(0.0000, -280.0000, 0)
	S032 = Part.Arc(P064, P065, P066)
	P067 = App.Vector(-197.9899, -197.9899, 0)
	P068 = App.Vector(-280.0000, -0.0000, 0)
	S033 = Part.Arc(P066, P067, P068)
	P069 = App.Vector(-200.9188, 190.9188, 0)
	P070 = App.Vector(-10.0000, 270.0000, 0)
	S034 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(173.8478, 193.8478, 0)
	P072 = App.Vector(250.0000, 10.0000, 0)
	S035 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(176.7767, -166.7767, 0)
	P074 = App.Vector(0.0000, -240.0000, 0)
	S036 = Part.Arc(P072, P073, P074)
	P075 = App.Vector(-169.7056, -169.7056, 0)
	P076 = App.Vector(-240.0000, -0.0000, 0)
	S037 = Part.Arc(P074, P075, P076)
	P077 = App.Vector(-172.6346, 162.6346, 0)
	P078 = App.Vector(-10.0000, 230.0000, 0)
	S038 = Part.Arc(P076, P077, P078)
	P079 = App.Vector(145.5635, 165.5635, 0)
	P080 = App.Vector(210.0000, 10.0000, 0)
	S039 = Part.Arc(P078, P079, P080)
	P081 = App.Vector(148.4924, -138.4924, 0)
	P082 = App.Vector(0.0000, -200.0000, 0)
	S040 = Part.Arc(P080, P081, P082)
	P083 = App.Vector(-141.4214, -141.4214, 0)
	P084 = App.Vector(-200.0000, -0.0000, 0)
	S041 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(-144.3503, 134.3503, 0)
	P086 = App.Vector(-10.0000, 190.0000, 0)
	S042 = Part.Arc(P084, P085, P086)
	P087 = App.Vector(117.2792, 137.2792, 0)
	P088 = App.Vector(170.0000, 10.0000, 0)
	S043 = Part.Arc(P086, P087, P088)
	P089 = App.Vector(120.2082, -110.2082, 0)
	P090 = App.Vector(0.0000, -160.0000, 0)
	S044 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(-113.1371, -113.1371, 0)
	P092 = App.Vector(-160.0000, -0.0000, 0)
	S045 = Part.Arc(P090, P091, P092)
	P093 = App.Vector(-116.0660, 106.0660, 0)
	P094 = App.Vector(-10.0000, 150.0000, 0)
	S046 = Part.Arc(P092, P093, P094)
	P095 = App.Vector(88.9949, 108.9949, 0)
	P096 = App.Vector(130.0000, 10.0000, 0)
	S047 = Part.Arc(P094, P095, P096)
	P097 = App.Vector(91.9239, -81.9239, 0)
	P098 = App.Vector(0.0000, -120.0000, 0)
	S048 = Part.Arc(P096, P097, P098)
	P099 = App.Vector(-84.8528, -84.8528, 0)
	P100 = App.Vector(-120.0000, -0.0000, 0)
	S049 = Part.Arc(P098, P099, P100)
	P101 = App.Vector(-87.7817, 77.7817, 0)
	P102 = App.Vector(-10.0000, 110.0000, 0)
	S050 = Part.Arc(P100, P101, P102)
	P103 = App.Vector(60.7107, 80.7107, 0)
	P104 = App.Vector(90.0000, 10.0000, 0)
	S051 = Part.Arc(P102, P103, P104)
	P105 = App.Vector(63.6396, -53.6396, 0)
	P106 = App.Vector(-0.0000, -80.0000, 0)
	S052 = Part.Arc(P104, P105, P106)
	P107 = App.Vector(-56.5685, -56.5685, 0)
	P108 = App.Vector(-80.0000, 0.0000, 0)
	S053 = Part.Arc(P106, P107, P108)
	P109 = App.Vector(-59.4975, 49.4975, 0)
	P110 = App.Vector(-10.0000, 70.0000, 0)
	S054 = Part.Arc(P108, P109, P110)
	P111 = App.Vector(32.4264, 52.4264, 0)
	P112 = App.Vector(50.0000, 10.0000, 0)
	S055 = Part.Arc(P110, P111, P112)
	P113 = App.Vector(35.3553, -25.3553, 0)
	P114 = App.Vector(-0.0000, -40.0000, 0)
	S056 = Part.Arc(P112, P113, P114)
	P115 = App.Vector(-28.2843, -28.2843, 0)
	P116 = App.Vector(-40.0000, 0.0000, 0)
	S057 = Part.Arc(P114, P115, P116)
	P117 = App.Vector(-31.2132, 21.2132, 0)
	P118 = App.Vector(-10.0000, 30.0000, 0)
	S058 = Part.Arc(P116, P117, P118)
	P119 = App.Vector(4.1421, 24.1421, 0)
	P120 = App.Vector(10.0000, 10.0000, 0)
	S059 = Part.Arc(P118, P119, P120)
	P121 = App.Vector(7.0711, 2.9289, 0)
	P122 = App.Vector(-0.0000, 0.0000, 0)
	S060 = Part.Arc(P120, P121, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceTop_Fa0():
	FC000 = ctr_face_spiral_faceTop_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def spiral_faceTop():
	FA000 = face_spiral_faceTop_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_spiral_faceSide_Fa0_Ctr0():
	P000 = App.Vector(-10.0000, 0.0000, 0)
	P001 = App.Vector(0.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-10.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-10.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa0():
	FC000 = ctr_face_spiral_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa1_Ctr0():
	P000 = App.Vector(10.0000, 0.0000, 0)
	P001 = App.Vector(20.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(20.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(10.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(10.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa1():
	FC000 = ctr_face_spiral_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa2_Ctr0():
	P000 = App.Vector(-50.0000, 0.0000, 0)
	P001 = App.Vector(-40.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-40.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-50.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-50.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa2():
	FC000 = ctr_face_spiral_faceSide_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa3_Ctr0():
	P000 = App.Vector(50.0000, 0.0000, 0)
	P001 = App.Vector(60.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(60.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(50.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(50.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa3():
	FC000 = ctr_face_spiral_faceSide_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa4_Ctr0():
	P000 = App.Vector(-90.0000, 0.0000, 0)
	P001 = App.Vector(-80.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-80.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-90.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-90.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa4():
	FC000 = ctr_face_spiral_faceSide_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa5_Ctr0():
	P000 = App.Vector(90.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(100.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(90.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(90.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa5():
	FC000 = ctr_face_spiral_faceSide_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa6_Ctr0():
	P000 = App.Vector(-130.0000, 0.0000, 0)
	P001 = App.Vector(-120.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-120.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-130.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-130.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa6():
	FC000 = ctr_face_spiral_faceSide_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa7_Ctr0():
	P000 = App.Vector(130.0000, 0.0000, 0)
	P001 = App.Vector(140.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(140.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(130.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(130.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa7():
	FC000 = ctr_face_spiral_faceSide_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa8_Ctr0():
	P000 = App.Vector(-170.0000, 0.0000, 0)
	P001 = App.Vector(-160.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-160.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-170.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-170.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa8():
	FC000 = ctr_face_spiral_faceSide_Fa8_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa9_Ctr0():
	P000 = App.Vector(170.0000, 0.0000, 0)
	P001 = App.Vector(180.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(180.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(170.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(170.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa9():
	FC000 = ctr_face_spiral_faceSide_Fa9_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa10_Ctr0():
	P000 = App.Vector(-210.0000, 0.0000, 0)
	P001 = App.Vector(-200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-200.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-210.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-210.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa10():
	FC000 = ctr_face_spiral_faceSide_Fa10_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa11_Ctr0():
	P000 = App.Vector(210.0000, 0.0000, 0)
	P001 = App.Vector(220.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(220.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(210.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(210.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa11():
	FC000 = ctr_face_spiral_faceSide_Fa11_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa12_Ctr0():
	P000 = App.Vector(-250.0000, 0.0000, 0)
	P001 = App.Vector(-240.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-240.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-250.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-250.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa12():
	FC000 = ctr_face_spiral_faceSide_Fa12_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa13_Ctr0():
	P000 = App.Vector(250.0000, 0.0000, 0)
	P001 = App.Vector(260.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(260.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(250.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(250.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa13():
	FC000 = ctr_face_spiral_faceSide_Fa13_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa14_Ctr0():
	P000 = App.Vector(-290.0000, 0.0000, 0)
	P001 = App.Vector(-280.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-280.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-290.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-290.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa14():
	FC000 = ctr_face_spiral_faceSide_Fa14_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_spiral_faceSide_Fa15_Ctr0():
	P000 = App.Vector(290.0000, 0.0000, 0)
	P001 = App.Vector(300.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(300.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(290.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(290.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spiral_faceSide_Fa15():
	FC000 = ctr_face_spiral_faceSide_Fa15_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def spiral_faceSide():
	FA000 = face_spiral_faceSide_Fa0()
	FA001 = face_spiral_faceSide_Fa1()
	FA002 = face_spiral_faceSide_Fa2()
	FA003 = face_spiral_faceSide_Fa3()
	FA004 = face_spiral_faceSide_Fa4()
	FA005 = face_spiral_faceSide_Fa5()
	FA006 = face_spiral_faceSide_Fa6()
	FA007 = face_spiral_faceSide_Fa7()
	FA008 = face_spiral_faceSide_Fa8()
	FA009 = face_spiral_faceSide_Fa9()
	FA010 = face_spiral_faceSide_Fa10()
	FA011 = face_spiral_faceSide_Fa11()
	FA012 = face_spiral_faceSide_Fa12()
	FA013 = face_spiral_faceSide_Fa13()
	FA014 = face_spiral_faceSide_Fa14()
	FA015 = face_spiral_faceSide_Fa15()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007, FA008, FA009, FA010, FA011, FA012, FA013, FA014, FA015])
	rOneFig.check()
	return rOneFig

def fex_subpax_spiral():
	FIG = spiral_faceTop()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_spiral = fex_subpax_spiral()

pax_spiral = subpax_spiral

pax_spiral.check()
#pax_spiral.exportBrep(f"{outFileName}.brep")
#pax_spiral.exportIges(f"{outFileName}.igs")
#pax_spiral.exportStep(f"{outFileName}.stp")
pax_spiral.exportStl(f"{outFileName}.stl")

